  repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-added-large-files

    - repo: local
      hooks:
        - id: create-venv
          name: Create Virtual Environment
          entry: make create-venv
          language: system
          pass_filenames: false
        - id: pylint
          name: Run pylint
          entry: ./venv/bin/pylint
          language: system
          types: [python]
          pass_filenames: true
          additional_dependencies: []
        - id: unittest
          name: Run unittest
          entry: ./venv/bin/python  # Path to the Python interpreter in your virtual environment
          args: ['-m', 'unittest', 'discover', '-v']
          language: system
          pass_filenames: false
          always_run: true

    - repo: https://github.com/commitizen-tools/commitizen
      rev: master
      hooks:
        - id: commitizen
        - id: commitizen-branch
          stages: [push]
