[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.0"
tag_format = "$version"
version_files = [
    "VERSION",
    "setup.py",
    "pyproject.toml:version"
]
bump_message = "bump: version $current_version → $new_version"
update_changelog_on_bump = true
annotated_tag = true
