name: Build

on:
  push:
    branches:
      - '**'  # All branches except tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make install

    - name: Run Linting
      run: |
        make lint

    - name: Run Tests
      run: |
        make test

    - name: Cache Build Artifacts
      uses: actions/cache@v4
      with:
        path: |
          venv
          build
        key: ${{ runner.os }}-build-${{ github.sha }}
