name: Release

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read CHANGELOG.md
      id: read_changelog
      run: |
        # Read the content of CHANGELOG.md into a variable
        changelog_content=$(cat CHANGELOG.md)
        echo "::set-output name=changelog::$changelog_content"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        body: ${{ steps.read_changelog.outputs.changelog }} # Using the content from CHANGELOG.md
        draft: false
        prerelease: false
