name: Release

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore Build Artifacts
      uses: actions/cache@v4
      with:
        path: |
          venv
          build
        key: ${{ runner.os }}-build-${{ github.sha }}

    - name: Create Bundle
      run: |
        make bundle-release

    - name: Read CHANGELOG.md
      id: read_changelog
      run: |
        changelog_content=$(cat CHANGELOG.md)
        echo "::set-output name=changelog::$changelog_content"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        body: ${{ steps.read_changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Upload Bundle to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/abletoolkit-bundle.zip
        asset_name: abletoolkit-bundle.zip
        asset_content_type: application/zip
